# Generated by Django 4.2.4 on 2023-09-06 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_remove_doctor_patient_remove_pharmacy_patient_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medication',
        ),
    ]
